### ISSUE TITLE
Add support for float and double values

### ISSUE THREAD

**Issue by joseluisgs** [ufoss-org/kotysa#110]
Hi
Is there support for double values? 
https://ufoss.org/kotysa/table-mapping.html#h2
I see integer, BiigInt...
thank you

**Comment by pull-vert** [comment]
Hi @joseluisgs 
double values are not yet supported, I plan it for 2.3.1 release (should be pretty soon, 2.3.0 is almost ready now !)

**Comment by joseluisgs** [comment]
Thank you!! :+1:  @pull-vert

**Comment by pull-vert** [comment]
hi @joseluisgs , Float, Double and Bigdecimal support was released yesterday in Kotysa 2.3.3 :slightly_smiling_face:

**Comment by joseluisgs** [comment]
Thank you so much. You are great!!!
💪💪
