### ISSUE TITLE
Add support NUMERIC type

### ISSUE THREAD

**Issue by ivan-kuritsyn** [ufoss-org/kotysa#122]
Hi
Is there any possibility to add support `NUMERIC` type for [PostgreSQL](https://ufoss.org/kotysa/table-mapping.html#postgresql)?
Thank you

**Comment by pull-vert** [comment]
Hi @ivan-kuritsyn 

I am currently working on a related issue to add Float / Real / Double precision support.
I add this to the next release scope.

**Comment by ivan-kuritsyn** [comment]
Hi @pull-vert !
Thank's so much!

**Comment by pull-vert** [comment]
hi @ivan-kuritsyn , `NUMERIC` and `DECIMAL` support was released yesterday in Kotysa 2.3.3 for PostgreSQL, H2, MySQL, MariaDB and Microsft SQL Server.
