### ISSUE TITLE
VertX coroutine support

### ISSUE THREAD

**Issue by guitcastro** [ufoss-org/kotysa#126]
It's possible to have a Vertex coroutine client as spring r2dbc?

**Comment by pull-vert** [comment]
Hello @guitcastro 

Yes it is possible, I changed the project roadmap to plan this feature in 3.1.0 release version

**Comment by pull-vert** [comment]
Hi @guitcastro 

This feature is now available in Kotysa 3.2.0, that was just released. A new sample project for Quarkus and coroutines was added : [kotysa-quarkus-vertx-sqlclient-coroutines](https://github.com/ufoss-org/kotysa/tree/master/samples/kotysa-quarkus-vertx-sqlclient-coroutines)

**Comment by guitcastro** [comment]
@pull-vert O this is wholesome!  

I was about to ask if you could  add support to transaction using co-routine context, but looking at the could, you [already done it](https://github.com/ufoss-org/kotysa/blob/bd16a40d140a72e54758a2929f4c543e62f3b8ea/kotysa-vertx-sqlclient/src/jvmMain/kotlin/org/ufoss/kotysa/vertx/CoroutinesSqlClientVertx.kt#L264). This is such a killer feature, I don´t know any ORM who can does that. Until now I had to use Uni in my code to compose transaction, and now I will be able to remove it.

**Comment by pull-vert** [comment]
Thanks a lot for this kind comment @guitcastro 

In fact for consistency I reused the same coroutine SQL query API and transaction storage in the coroutine context as in the existing kotysa-r2dbc module.
I'm glad that this implementation suits you !
