### ISSUE TITLE
Add support to contains ignoring cases

### ISSUE THREAD

**Issue by guitcastro** [ufoss-org/kotysa#137]
added the `.containsIgnoreCase` operation.

**Comment by pull-vert** [comment]
Hi @guitcastro 

This feature is indeed useful, I will to find the right way to do it for every supported databases.
PostgreSQL supports iLIKE operator, for others it seems like I can use `UPPER(value)` function.
I'll have to add `startsWithIgnoreCase` and `endsWithIgnoreCase` as well.

**Comment by guitcastro** [comment]
In my case, ILIKE operator would work because I am using postgreqll. Using UPPER would work for most of the cases. I think we might add a "custom" operation where users can defined their own fragments of sql.

**Comment by pull-vert** [comment]
I will start simple at first :slightly_smiling_face:

**Comment by pull-vert** [comment]
Hi @guitcastro 
This feature is included in the latest 3.2.2 version that was released yesterday
