### ISSUE TITLE
SelectSum is only available for IntColumn

### ISSUE THREAD

**Issue by guitcastro** [ufoss-org/kotysa#143]
Make `selectSum` available for `NumericColumn` as `selectAvg`

**Comment by guitcastro** [comment]
Ok! I need `selectSum` to aggregate transaction values. For now, I am just selecting all values and summing in the client side. 

I would love to create a PR to fix it, but for now we are too busy with dead lines. I hope this change too so I can give back to this project!

**Comment by pull-vert** [comment]
thanks a lot in advance, I must admit that I am strongly busy at work and with family life too :slightly_smiling_face: 
I started to work on the 3.1.0 issues, I am planning to release it in July I think.

**Comment by guitcastro** [comment]
@pull-vert Take your time, I am just creating the issues because it's what I can do to help for now. Anyway, thanks for the awesome project :)
