### ISSUE TITLE
Add LIMIT and OFFSET support

### ISSUE THREAD

**Issue by dave08** [ufoss-org/kotysa#37]
Usually needed for pagination in apis...

**Comment by pull-vert** [comment]
Thanks for this request, I plan this feature for 0.2.1 release because the next release (0.2.0) is already pretty busy :)

**Comment by pull-vert** [comment]
@dave08 Kotysa 0.2.1 was release, you can now use LIMIT and OFFSET with Kotysa :)

```kotlin
val paginated = (sqlClient selectFrom USER
        limit 10 offset 12
        ).fetchAll()
```

**Comment by dave08** [comment]
Nice :+1:, thanks!
